# Generated by Django 4.0.5 on 2022-06-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ST', 'Study'), ('PJ', 'Project'), ('EX', 'Exhibition')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
