# Generated by Django 4.0.5 on 2022-06-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_comment_author_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
